"""
WhatsApp account-linking routes (§37 Phase 13, file 18 prompt 1).

Thin HTTP wrappers around `WhatsAppLinkService` (`app/whatsapp/linking.py`) -- same
split as `app.api.routes.push` over `PushSubscriptionService` (§41 Rule 7): these
routes validate the request, call the service, and shape the response; code
generation, expiry, and the single-use/re-pair rules all live in the service.

Every route here requires a valid bearer token (`get_current_user`, router-level
dependency), the same boundary `push`/`routines`/`discord` use. That is the whole
point of this half of the flow: the pairing code is generated by someone who has
*already* proved who they are over HTTP, which is what lets the webhook trust a bare
phone number later. `whatsapp_access_token`/`whatsapp_app_secret` never cross this
boundary -- nothing here reads them, and the status response says only whether a
number is linked.

The inbound webhook is deliberately **not** in this module. It arrives from Meta with
no bearer token (its caller identity is the `X-Hub-Signature-256` HMAC instead), so it
cannot live under this router's blanket `get_current_user` dependency -- file 18
prompt 2 adds it as its own module, `app/api/routes/whatsapp_webhook.py`.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.api.dependencies import get_current_user
from app.database.database import get_db
from app.database.models import User
from app.platforms.whatsapp import is_configured
from app.whatsapp.linking import LINK_CODE_TTL_MINUTES, WhatsAppLinkService

router = APIRouter(prefix="/whatsapp", tags=["whatsapp"], dependencies=[Depends(get_current_user)])


class LinkCodeOut(BaseModel):
    """The pairing code, plus both forms of its lifetime: `expires_at` for display and
    `expires_in_seconds` so a countdown doesn't have to reconcile the backend's clock
    with the browser's.
    """

    code: str
    expires_at: datetime
    expires_in_seconds: int


class LinkStatusOut(BaseModel):
    # Whether the *backend* has WhatsApp credentials at all (`is_configured`), as
    # opposed to whether this user has linked a number. Both false is the pre-setup
    # state, and the settings UI has to say something different in each case: a pairing
    # code generated against a backend with no Meta app behind it can never be
    # delivered, so the UI points at docs/deployment.md instead of offering the button.
    # Same role `DiscordStatusOut.configured` plays for the Discord panel.
    configured: bool
    linked: bool
    # The user's own linked number, returned in full -- it's their number, and this
    # route only ever answers for the authenticated caller.
    phone_number: str | None = None
    # Whether a generated code is still outstanding. The code itself is never returned
    # here: it's handed out exactly once, by the POST that created it, so reloading the
    # settings page can't re-reveal a code left on someone else's screen.
    code_pending: bool = False
    code_expires_at: datetime | None = None


@router.post("/link-code", response_model=LinkCodeOut, status_code=201)
def create_link_code(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> LinkCodeOut:
    # Always issues a *new* code and invalidates any previous one (see
    # `generate_link_code`'s docstring), so pressing the button twice is safe and the
    # second code is the only one that works.
    code, expires_at = WhatsAppLinkService(db).generate_link_code(current_user.id)
    return LinkCodeOut(
        code=code,
        expires_at=expires_at,
        expires_in_seconds=LINK_CODE_TTL_MINUTES * 60,
    )


@router.get("/link", response_model=LinkStatusOut)
def get_link_status(current_user: User = Depends(get_current_user)) -> LinkStatusOut:
    return LinkStatusOut(
        configured=is_configured(),
        linked=current_user.whatsapp_phone_number is not None,
        phone_number=current_user.whatsapp_phone_number,
        code_pending=current_user.whatsapp_link_code is not None,
        code_expires_at=current_user.whatsapp_link_code_expires_at,
    )


@router.delete("/link", status_code=204, response_model=None)
def unlink(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> None:
    # 404 when there was nothing to unlink, mirroring `DELETE /api/push/subscribe`.
    # Scoped to the authenticated user by construction -- there is no way to name
    # someone else's number here.
    if not WhatsAppLinkService(db).unlink(current_user.id):
        raise HTTPException(status_code=404, detail="No WhatsApp number is linked to this account.")
